In [30]:
import plotly.express as px
import pandas as pd

In [31]:
df = pd.read_csv('/Users/I578070/Desktop/100DaysML/Datasets/sample_data.csv')

In [32]:
df.head()

   Country  Gender  Age   Color   Pay
0   Canada  Female   31  Yellow  9038
1   Canada  Female   63  Orange  8496
2   Canada  Female   35     Red  5598
3  Germany    Male   61  Orange  8342
4       UK  Female   54     Red  5218

In [33]:
df.shape

(100, 5)

In [34]:
px.bar(df, x='Country',y='Pay',color='Pay')

In [35]:
df1 = df.groupby(['Country']).size().rename('Count').reset_index()

In [36]:
df.head()

   Country  Gender  Age   Color   Pay
0   Canada  Female   31  Yellow  9038
1   Canada  Female   63  Orange  8496
2   Canada  Female   35     Red  5598
3  Germany    Male   61  Orange  8342
4       UK  Female   54     Red  5218

In [37]:
df.head()

   Country  Gender  Age   Color   Pay
0   Canada  Female   31  Yellow  9038
1   Canada  Female   63  Orange  8496
2   Canada  Female   35     Red  5598
3  Germany    Male   61  Orange  8342
4       UK  Female   54     Red  5218

In [38]:
px.bar(df1, x='Country', y='Count', color='Country',color_discrete_sequence=['red', 'blue', 'green', 'yellow', 'orange'],text='Count')

In [39]:
px.data.gapminder()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4
...,...,...,...,...,...,...,...,...
1699,Zimbabwe,Africa,1987,62.351,9216418,706.157306,ZWE,716
1700,Zimbabwe,Africa,1992,60.377,10704340,693.420786,ZWE,716
1701,Zimbabwe,Africa,1997,46.809,11404948,792.449960,ZWE,716
1702,Zimbabwe,Africa,2002,39.989,11926563,672.038623,ZWE,716
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

# Line Plot

In [49]:
df = px.data.gapminder().query('country==["Canada","Afghanistan","United States"]')

In [50]:
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [53]:
fig = px.line(df,x ='year', y='lifeExp',color='country' ,title='Life Expectancy in Canada')
fig.show()

# ScatterPlot

In [55]:
fig = px.scatter([1,2,3,4,5],[10,11,12,13,14],title='Simple Scatter Plot')
fig.show()

In [56]:
iris = pd.read_csv('/Users/I578070/Desktop/100DaysML/Datasets/datasets-session-24/iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [68]:
fig = px.scatter(iris, x='SepalLengthCm',y='SepalWidthCm',color='Species',title='Iris Dataset Sepal Length vs Width',size='PetalLengthCm',trendline="ols")

fig.show()

# Histogram

In [69]:
tips = px.data.tips()

In [71]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [74]:
fig = px.histogram(tips, x='total_bill', color='smoker', title='Total Bill Distribution by Smoker Status')
fig.show()

# BoxPlot

In [76]:
fig = px.box(tips, y= 'total_bill')
fig.show()

# Violin Plot

In [77]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [79]:
fig = px.violin(tips, x='total_bill',y='day',color='day')
fig.show()